title: deluca
logo: https://raw.githubusercontent.com/MinRegret/deluca/dev/assets/img/deluca.svg?token=AAURLVRRLKHPK4VELPKH6X27RW5LC
description: Performant, differentiable reinforcement learning
show_downloads: false
theme: jekyll-theme-minimal
google_analytics:
